var myTopnav="";


  myTopnav += '<nav class='navbar navbar-default navbar-fixed-top navbar-inverse' style='font-size: large;'>";
  myTopnav += '  <div class='container-fluid'>";
  myTopnav += '    <!-- Brand and toggle get grouped for better mobile display -->";
  myTopnav += '    <div class='navbar-header'>";
  myTopnav += '      ";
  myTopnav += '      <a class='navbar-brand' href='index.HTML'>";
  myTopnav += '        <img alt='Logo' src='image/LogoSfondi/Logo.PNG'>";
  myTopnav += '      </a>";
  myTopnav += '    </div>";
  myTopnav += '";
  myTopnav += '    <!-- Collect the nav links, forms, and other content for toggling -->";
  myTopnav += '    <div class='collapse navbar-collapse' id='bs-example-navbar-collapse-1'>";
  myTopnav += '      <ul class='nav navbar-nav'>";
  myTopnav += '        <li><a href='#'>Home <span class='sr-only'>(current)</span></a></li>";
  myTopnav += '        <li><a href='#'>Login</a></li>";
  myTopnav += '        <li class='dropdown'>";
  myTopnav += '          <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-haspopup='true'";
  myTopnav += '            aria-expanded='false'>Prodotti <span class='caret'></span></a>";
  myTopnav += '          <ul class='dropdown-menu'>";
  myTopnav += '            <li><a href='oli.html'>Olii</a></li>";
  myTopnav += '            <li><a href='Beauty.html'>Creme</a></li>";
  myTopnav += '            <li><a href='prodotti.html'>Tinte</a></li>";
  myTopnav += '            <li role='separator' class='divider'></li>";
  myTopnav += '            <li><a href='#'>MappaSito</a></li>";
  myTopnav += '            <li role='separator' class='divider'></li>";
  myTopnav += '            <li><a href='#'>Henné</a></li>";
  myTopnav += '          </ul>";
  myTopnav += '        </li>";
  myTopnav += '      </ul>";
  myTopnav += '      <ul class='nav navbar-nav navbar-right'>";
  myTopnav += '        <li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>";
  myTopnav += '        <li class='dropdown'>";
  myTopnav += '          <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-haspopup='true'";
  myTopnav += '            aria-expanded='false'><i class='fa fa-user'></i> <span class='caret'></span></a>";
  myTopnav += '          <ul class='dropdown-menu'>";
  myTopnav += '            <li class='dropdown-header'>Profilo</li>";
  myTopnav += '            <li><a href='#'>Account</a></li>";
  myTopnav += '            <li><a href='linee.html'>Linee</a></li>";
  myTopnav += '            <li><a href='vantaggi.html'>Vantaggi</a></li>";
  myTopnav += '            <li role='separator' class='divider'></li>";
  myTopnav += '            <li class='dropdown-header'>Info</li>";
  myTopnav += '            <li><a href='faqXML.html'>Faq</a></li>";
  myTopnav += '          </ul>";
  myTopnav += '        </li>";
  myTopnav += '      </ul>";
  myTopnav += '    </div><!-- /.navbar-collapse -->";
  myTopnav += '  </div><!-- /.container-fluid -->";
  myTopnav += '</nav>";


