var myTopnav = "";

myToponav += "<nav class='navbar navbar-default navbar-fixed-top navbar-inverse' style='font-size: large;'>";
myToponav += "	<div class='container-fluid'>";
myToponav += "	  <!-- Brand and toggle get grouped for better mobile display -->";
myToponav += "	  <div class='navbar-header'>";
myToponav += "		<button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#bs-example-navbar-collapse-1' aria-expanded='false'>";
myToponav += "		  <span class='sr-only'>Toggle navigation</span>";
myToponav += "		  <span class='icon-bar'></span>";
myToponav += "		  <span class='icon-bar'></span>";
myToponav += "		  <span class='icon-bar'></span>";
myToponav += "		</button>";
myToponav += "		";
myToponav += "		</div>";
myToponav += "	  <!-- Collect the nav links, forms, and other content for toggling -->";
myToponav += "	  <div class='collapse navbar-collapse' id='bs-example-navbar-collapse-1'>";
myToponav += "		<ul class='nav navbar-nav'>";
myToponav += "		  <li><a href='index.html'>Home<span class='sr-only'>(current)</span></a></li>";
myToponav += "		  <li><a href='#'>Sull'Azienda</a></li>";
myToponav += "		  <li class='dropdown'>";
myToponav += "			<a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false'>Prodotti<span class='caret'></span></a>";
myToponav += "			<ul class='dropdown-menu'>";
myToponav += "				<li><a href='Beauty.php'>Cura dei capelli</a></li>";
myToponav += "				<li><a href='Olii.php'>Oli Essenziali</a></li>";
myToponav += "				<li><a href='Henne.php'>Hennè</a></li>";
myToponav += "				<li role='separator' class='divider'></li>";
myToponav += "				<li class='dropdown-header'>omeoTINTS</li>";
myToponav += "				<li><a href='Tinte.php?IDGrp=1'>Serie Naturali</a></li>";
myToponav += "				<li><a href='Tinte.php?IDGrp=2'>Serie Dorati</a></li>";
myToponav += "				<li><a href='Tinte.php?IDGrp=3'>Serie Rossi - Mogano</a></li>";
myToponav += "			</ul>";
myToponav += "		  </li>";
myToponav += "		</ul>";
myToponav += "		<form class='navbar-form navbar-left hidden' style='padding-top: 10px;'>";
myToponav += "		  <div class='form-group'>";
myToponav += "			<input type='text' class='form-control' placeholder='Inserisci parola chiave'>";
myToponav += "		  </div>";
myToponav += "		  <button type='submit' class='btn btn-default'>Cerca</button>";
myToponav += "		</form>";
myToponav += "		<ul class='nav navbar-nav navbar-right hidden'>";
myToponav += "			<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>";
myToponav += "			<li class='dropdown'>";
myToponav += "				<a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-haspopup='true'";
myToponav += "				aria-expanded='false'><i class='fa fa-user'></i> <span class='caret'></span></a>";
myToponav += "				<ul class='dropdown-menu'>";
myToponav += "					<li class='dropdown-header'>Profilo</li>";
myToponav += "					<li><a href='account.html'>Account</a></li>";
myToponav += "					<li><a href='login.html'>Login</a></li>";
myToponav += "					<li role='separator' class='divider'></li>";
myToponav += "					<li class='dropdown-header'>Informazioni</li>";
myToponav += "					<li><a href='faqXML.html'>Faq</a></li>";
myToponav += "					<li><a href='lineeGuida.html'>Linee Guida</a></li>";
myToponav += "			</ul>";
myToponav += "		  </li>";
myToponav += "		</ul>";
myToponav += "	  </div><!-- /.navbar-collapse -->";
myToponav += "	</div><!-- /.container-fluid -->";
myToponav += "</nav>";

myTopnav += "<nav class='navbar navbar-default navbar-fixed-top navbar-inverse' style='font-size: large;'>";
myTopnav += "	<div class='container-fluid'>";
myTopnav += "	  <!-- Brand and toggle get grouped for better mobile display -->";
myTopnav += "	  <div class='navbar-header'>";
myTopnav += "		<button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#bs-example-navbar-collapse-1' aria-expanded='false'>";
myTopnav += "		  <span class='sr-only'>Toggle navigation</span>";
myTopnav += "		  <span class='icon-bar'></span>";
myTopnav += "		  <span class='icon-bar'></span>";
myTopnav += "		  <span class='icon-bar'></span>";
myTopnav += "		</button>";
myTopnav += "		";
myTopnav += "		</div>";
myTopnav += "	  <!-- Collect the nav links, forms, and other content for toggling -->";
myTopnav += "	  <div class='collapse navbar-collapse' id='bs-example-navbar-collapse-1'>";
myTopnav += "		<ul class='nav navbar-nav'>";
myTopnav += "		  <li><a href='index.html'>Home<span class='sr-only'>(current)</span></a></li>";
myTopnav += "		  <li><a href='#'>Sull'Azienda</a></li>";
myTopnav += "		  <li class='dropdown'>";
myTopnav += "			<a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false'>Prodotti<span class='caret'></span></a>";
myTopnav += "			<ul class='dropdown-menu'>";
myTopnav += "				<li><a href='Beauty.php'>Cura dei capelli</a></li>";
myTopnav += "				<li><a href='Olii.php'>Oli Essenziali</a></li>";
myTopnav += "				<li><a href='Henne.php'>Hennè</a></li>";
myTopnav += "				<li role='separator' class='divider'></li>";
myTopnav += "				<li class='dropdown-header'>omeoTINTS</li>";
myTopnav += "				<li><a href='Tinte.php?IDGrp=1'>Serie Naturali</a></li>";
myTopnav += "				<li><a href='Tinte.php?IDGrp=2'>Serie Dorati</a></li>";
myTopnav += "				<li><a href='Tinte.php?IDGrp=3'>Serie Rossi - Mogano</a></li>";
myTopnav += "			</ul>";
myTopnav += "		  </li>";
myTopnav += "		</ul>";
myTopnav += "		<form class='navbar-form navbar-left hidden' style='padding-top: 10px;'>";
myTopnav += "		  <div class='form-group'>";
myTopnav += "			<input type='text' class='form-control' placeholder='Inserisci parola chiave'>";
myTopnav += "		  </div>";
myTopnav += "		  <button type='submit' class='btn btn-default'>Cerca</button>";
myTopnav += "		</form>";
myTopnav += "		<ul class='nav navbar-nav navbar-right hidden'>";
myTopnav += "			<li><a href='#'><i class='fa fa-shopping-cart'></i></a></li>";
myTopnav += "			<li class='dropdown'>";
myTopnav += "				<a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-haspopup='true'";
myTopnav += "				aria-expanded='false'><i class='fa fa-user'></i> <span class='caret'></span></a>";
myTopnav += "				<ul class='dropdown-menu'>";
myTopnav += "					<li class='dropdown-header'>Profilo</li>";
myTopnav += "					<li><a href='account.html'>Account</a></li>";
myTopnav += "					<li><a href='login.html'>Login</a></li>";
myTopnav += "					<li role='separator' class='divider'></li>";
myTopnav += "					<li class='dropdown-header'>Informazioni</li>";
myTopnav += "					<li><a href='faqXML.html'>Faq</a></li>";
myTopnav += "					<li><a href='lineeGuida.html'>Linee Guida</a></li>";
myTopnav += "			</ul>";
myTopnav += "		  </li>";
myTopnav += "		</ul>";
myTopnav += "	  </div><!-- /.navbar-collapse -->";
myTopnav += "	</div><!-- /.container-fluid -->";
myTopnav += "</nav>";
